version: '2'

volumes:
  mariadb-data:
    driver: local

services:
  mariadb:
    tty: true
    image: bitnami/mariadb:latest
    volumes:
      - mariadb-data:/bitnami/mariadb

  myapp:
    tty: true
    # build: .
    image: gcr.io/bitnami-containers/rails:4.2.6-r1
    environment:
      - DATABASE_URL=mysql2://mariadb/my_app_development
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - .:/app
