version: '2'

volumes:
  mariadb-data:
    driver: local

services:
  mariadb:
    tty: true
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_USER=
      - MARIADB_PASSWORD=
      - MARIADB_DATABASE=
    volumes:
      - mariadb-data:/bitnami/mariadb

  myapp:
    tty: true
    build: .
    environment:
      - DATABASE_URL=mysql2://mariadb/my_app_development
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
